func_aux.h File Reference
Funciones auxiliares assembly.
Functions
int * get_ebp ()
funcion get_ebp
int * get_next_ebp (int *)
funcion get_next_ebp
int get_int_value (int *, int)
funcion get_int_value
char get_char_value (int *, int)
funcion get_char_value
float get_float_value (int *, int)
funcion get_float_value
double get_double_value (int *, int)
funcion get_double_value
char * get_string_value (int *, int)
funcion get_string_value
void * get_void_value (int *, int)
funcion get_void_value
char ** get_string_array_value (int *, int)
funcion get_string_array_value
char * get_function_return (int *)
funcion get_function_return
Detailed Description
Funciones auxiliares assembly. Este archivo consta de las implementacion de las funciones definidas en los protottipos
Author
Calvo Alfaro, Angelo Alejandro (acalvoa)
Bug
Bug No conocidos
Function Documentation
char get_char_value (int * , int)
funcion get_char_value
funcion que recupera el valor del parametro relativo a ebp a partir de un offset
Parameters
int* proporciona un puntero al stack frame
int correponde al offset relativo al ebp
Returns
la funcion retorna el valor char del argumento
Referenced by print_args().
double get_double_value (int * , int)
funcion get_double_value
funcion que recupera el valor del parametro relativo a ebp a partir de un offset
Parameters
int* proporciona un puntero al stack frame
int correponde al offset relativo al ebp
Returns
la funcion retorna el valor double del argumento
Referenced by print_args().
int* get_ebp ()
funcion get_ebp
funcion que recupera un puntero a la posicion del stack frame
Returns
la funcion retorna un puntero al stack frame que llamo a la funcion traceback
Referenced by traceback().
float get_float_value (int * , int)
funcion get_float_value
funcion que recupera el valor del parametro relativo a ebp a partir de un offset
Parameters
int* proporciona un puntero al stack frame
int correponde al offset relativo al ebp
Returns
la funcion retorna el valor float del argumento
Referenced by print_args().
char* get_function_return (int *)
funcion get_function_return
funcion que recupera el valor de retorno de la funcion de ebp a partir de un stack frame
Parameters
int* proporciona un puntero al stack frame
Returns
la funcion retorna un puntero al vaor de retorno
Referenced by search_function().
int get_int_value (int * , int)
funcion get_int_value
funcion que recupera el valor del parametro relativo a ebp a partir de un offset
Parameters
int* proporciona un puntero al stack frame
int correponde al offset relativo al ebp
Returns
la funcion retorna el valor int del argumento
Referenced by print_args().
int* get_next_ebp (int *)
funcion get_next_ebp
funcion que recupera un puntero al siguiente posicion del stack frame a partir de uno ya existente
Parameters
int* proporciona un puntero al stack frame
Returns
la funcion retorna un puntero al siguiente stack frame
Referenced by traceback().
char** get_string_array_value (int * , int)
funcion get_string_array_value
funcion que recupera el valor del parametro relativo a ebp a partir de un offset
Parameters
int* proporciona un puntero al stack frame
int correponde al offset relativo al ebp
Returns
la funcion retorna el valor char** del argumento
Referenced by print_args().
char* get_string_value (int * , int)
funcion get_string_value
funcion que recupera el valor del parametro relativo a ebp a partir de un offset
Parameters
int* proporciona un puntero al stack frame
int correponde al offset relativo al ebp
Returns
la funcion retorna el valor string del argumento
Referenced by print_args().
void* get_void_value (int * , int)
funcion get_void_value
funcion que recupera el valor del parametro relativo a ebp a partir de un offset
Parameters
int* proporciona un puntero al stack frame
int correponde al offset relativo al ebp
Returns
la funcion retorna el valor void* del argumento
Referenced by print_args().