string_aux.h File Reference
Funciones prototipo auxiliares de String.
#include `string.h`
*
#include `stdlib.h`
*
Functions
size_t strlen (const char *str)
funcion para contar largo de strings - strlen
char * substr (char *cadena, int comienzo, int longitud)
funcion para cortar strings - substr
int ischar (char *cadena)
funcion para identificar char string
Detailed Description
Funciones prototipo auxiliares de String. Este archivo consta de dos funciones auxiliares para la manipulacion de String que son strlen y substr. Estas funciones son necesarias para el correcto funcionamiento de traceback.
Author
Calvo Alfaro, Angelo Alejandro (acalvoa)
Bug
Bug No conocidos
Function Documentation
int ischar (char * cadena)
funcion para identificar char string
Esta funcion identifica si el char* es un string
Parameters
cadena Representa el string a analizar
Returns
La funcion retorna un 1 si es char o un 0 si es string
Referenced by print_args().
size_t strlen (const char * str)
funcion para contar largo de strings - strlen
Esta funcion cuenta la cantidad de caracteres validos presentes en un string.
Parameters
str representa el string que se obtendra su largo.
Returns
La funcion retorna el largo del string suministrado.
Referenced by isprint_string(), locate_function(), print_args(), and substr().
char* substr (char * cadena, int comienzo, int longitud)
funcion para cortar strings - substr
Esta funcion corta un string en una cantidad definida por el usuario.
Parameters
cadena Representa el string a cortar
comienzo Indica la posicion del arreglo char* en donde se comienza a cortar la cadena.
longitud Indica el largo que tendra la cadena
Returns
La funcion retorna el string cortado de acuerdo al largo especificado y se añade al final de este puntos suspensivos.
References strlen().
Referenced by print_args().