traceback.h File Reference
funciones prototipo de la libreria traceback
#include <stdio.h>
*
Functions
void traceback (FILE *)
funcion print_func
Detailed Description
funciones prototipo de la libreria traceback No borrar este archivo. Contiene las definiciones abstractas de la libreria trace
Author
Calvo Alfaro, Angelo Alejandro (acalvoa)
Bug
Bug No conocidos
Function Documentation
void traceback (FILE * fp)
funcion print_func
print_func es una funcion recursiva que se encarga de recorrer el stack, recorriendo los stack frames hasta el wrapper. Para esto hace uso del registro ebp y mueve el puntero hasta que no se enceuntran mas funciones despues del wrapper que corresponde a un indice -1.
Parameters
*fp correponde al puntero a un stack
Returns
la funcion no retorna valores.
References get_ebp(), get_next_ebp(), print_func(), and search_function().