traceback.c File Reference
La funcion Traceback.
#include `traceback_internal.h`
*
#include `func_aux.h`
*
#include `ctype.h`
*
#include `string_aux.h`
*
Functions
int locate_function (int num, char *instruction)
funcion locate_function
int search_function (int *ebp)
funcion search_function
int isprint_string (char *string)
funcion isprint_string
void print_args (const functsym_t func, int i, int *ebp, int first)
funcion print_args
void print_func (int pos, int *ebp, int *main, int *first)
funcion print_func
void traceback (FILE *fp)
funcion print_func
Detailed Description
La funcion Traceback. Este archivo contiene la funcion traceback y todas las funciones auxiliares adicionales necesarias para la ejecución de traceback. las funciones del archivo corresponden a funciones necesarias por el la funcion traceback para operar de forma recursiva a traves de la tabla de funciones generada. Las busquedas en esta tabla son efectuadas a traves de metodos recursivos en base a las especificaciones indicadas en el documento de requerimiento.
Author
Calvo Alfaro, Angelo Alejandro (acalvoa)
Bug
Bug No conocidos
Function Documentation
int isprint_string (char * string)
funcion isprint_string
funcion que indica si un string valido apra ser impresa
Parameters
string provee el string que debe ser analizado
Returns
la funcion retorna un 1 en caso de que el string se pueda imprimir o un 0 en caso de que no pueda ser impreso.
References strlen().
Referenced by print_args().
int locate_function (int num, char * instruction)
funcion locate_function
funcion que busca de forma iterativa en la tabla de funciones a partir de una direccion de memoria obtenida de las instrucciones previas a la direccion de retorno con respecto a ebp
Parameters
num indica el numero incremental recursivo. Siempre debe ser cero al efectuarse la primera llamada.
instruction corresponde a un puntero de 1 byte a la direccion de llamada de la funcion a buscar
Returns
la funcion retorna el indice de coincidencia con la tabla de funciones.
References strlen().
Referenced by search_function().
void print_args (const functsym_t func, int i, int * ebp, int first)
funcion print_args
print_args es una funcion recursiva que se encarga de imprimir en pantalla todos los argumentos de una funcion que ha sido identificada a partir de su stack frame el formato bajo el cual se imprimen dichos parametros corresponde al requerido por el documento de requerimientos.
Parameters
func es la funcion que ha sido identificada de la tabla
i corresponde al valor recursivo, siempre debe ser 0
ebp correponde al puntero hacia el stack frame
first es un puntero que debe ser siempre 1.
Returns
la funcion no retorna valores.
References get_char_value(), get_double_value(), get_float_value(), get_int_value(), get_string_array_value(), get_string_value(), get_void_value(), ischar(), isprint_string(), strlen(), and substr().
Referenced by print_func().
void print_func (int pos, int * ebp, int * main, int * first)
funcion print_func
print_func es una funcion que a partir de la posicion de la funcion en la tabla y del stack frame idetificado imprime la funcion de acuerdo al formato planteado en la hoja de requerimientos.
Parameters
pos correponde a la posicion dentro de la tabla
ebp correponde al puntero hacia el stack frame
main es un puntero que indica si ya hubo coicidecia con main siempre debe ser 0
first es un puntero que debe ser siempre 1.
Returns
la funcion no retorna valores.
References print_args().
Referenced by traceback().
int search_function (int * ebp)
funcion search_function
funcion que busca a que funcion de la tabla corresponde un stack frame determianado.
Parameters
ebp indica el stack frame a analizar
Returns
la funcion retorna la posicion de la funcion que coincide de la tabla de funciones o un -1 en caso de no existir coincidencias
References get_function_return(), and locate_function().
Referenced by traceback().
void traceback (FILE * fp)
funcion print_func
print_func es una funcion recursiva que se encarga de recorrer el stack, recorriendo los stack frames hasta el wrapper. Para esto hace uso del registro ebp y mueve el puntero hasta que no se enceuntran mas funciones despues del wrapper que corresponde a un indice -1.
Parameters
*fp correponde al puntero a un stack
Returns
la funcion no retorna valores.
References get_ebp(), get_next_ebp(), print_func(), and search_function().